name: CI
on: [pull_request]

jobs:
  validate:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [format, lint, typecheck, test, build]
        node-version: [20, 21, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up Turborepo
        uses: ./.github/actions/set-up-turborepo
        with:
          task: ${{ matrix.task }}
          node-version: ${{ matrix.node-version }}

      - name: Run turbo task - ${{ matrix.task }} (node${{ matrix.node-version }})
        run: pnpm ${{ matrix.task }}
