name: Publish Chess package
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'publish-chess'
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for semver change
        id: version-check
        uses: ./.github/actions/check-semver-change
        with:
          path: 'packages/chess'

      - name: Set-up Turborepo
        if: steps.version-check.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/set-up-turborepo
        with:
          node-version: 22
          task: 'publish-chess'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepublish package
        if: steps.version-check.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: pnpm prepublishOnly --filter @chess-broadcaster-suite/chess

      - name: Publish package
        if: steps.version-check.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: pnpm publish --filter @chess-broadcaster-suite/chess
